import { useEffect, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { Asset } from 'expo-asset';
import * as SplashScreen from 'expo-splash-screen';
import { WebView } from 'react-native-webview';

/* Keep the native splash up until the game has actually rendered. */
SplashScreen.preventAutoHideAsync().catch(() => {});

/**
 * The whole app is the game: a WKWebView loading the self-contained
 * game bundle from the app package (works fully offline — Web Audio,
 * localStorage best scores and the local leaderboard all live inside
 * the WebView; PlayFab, when configured at build time, uses HTTPS).
 *
 * The bundle is generated by `bun run build:mobile` at the repo root.
 */
export default function App() {
  const [gameUri, setGameUri] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      try {
        const asset = Asset.fromModule(require('./assets/game/index.html'));
        await asset.downloadAsync();
        setGameUri(asset.localUri ?? asset.uri);
      } catch (e) {
        setError(String(e));
        SplashScreen.hideAsync().catch(() => {});
      }
    })();
  }, []);

  return (
    <View style={styles.root}>
      <StatusBar hidden />
      {gameUri && (
        <WebView
          style={styles.web}
          source={{ uri: gameUri }}
          originWhitelist={['*']}
          allowFileAccess
          allowFileAccessFromFileURLs
          domStorageEnabled
          javaScriptEnabled
          allowsInlineMediaPlayback
          mediaPlaybackRequiresUserAction={false}
          bounces={false}
          scrollEnabled={false}
          overScrollMode="never"
          setBuiltInZoomControls={false}
          contentInsetAdjustmentBehavior="never"
          webviewDebuggingEnabled={__DEV__}
          onLoadEnd={() => SplashScreen.hideAsync().catch(() => {})}
        />
      )}
      {error && <Text style={styles.error}>Failed to load game: {error}</Text>}
    </View>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#05050a'
  },
  web: {
    flex: 1,
    backgroundColor: '#05050a'
  },
  error: {
    color: '#c6c6de',
    fontFamily: 'Courier',
    padding: 24,
    textAlign: 'center'
  }
});
